# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pdf-inspector}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gregory Brown", "Daniel Nelson", "Brad Ediger", "Micha\303\253l Witrant"]
  s.date = %q{2010-09-27}
  s.description = %q{A collection of PDF::Reader based analysis classes for inspecting PDF output. Mainly used for testing Prawn, but will work with any PDF}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "Rakefile",
     "VERSION",
     "lib/pdf/inspector.rb",
     "lib/pdf/inspector/extgstate.rb",
     "lib/pdf/inspector/graphics.rb",
     "lib/pdf/inspector/page.rb",
     "lib/pdf/inspector/text.rb",
     "lib/pdf/inspector/xobject.rb"
  ]
  s.homepage = %q{http://github.com/bastien/pdf-inspector}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Tools to inspect pdf outputs}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

